apiVersion: v1
kind: Pod
metadata:
  name: pod-lister
  namespace: default
spec:
  serviceAccountName: pod-lister
  containers:
    - name: pod-lister
      image: norriswu2666/norris-test:latest
      volumeMounts:
        - name: sa-token
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          readOnly: true
  volumes:
    - name: sa-token
      projected:
        sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 3600
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    fieldPath: metadata.namespace
  restartPolicy: Never
